server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: group3
    password: group3
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
       format_sql: true
       show_sql: true
      
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace